[workspace]
authors = ["Childhod Cancer Data Lab"]
channels = ["conda-forge", "bioconda"]
name = "training-specific-template"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
setup = "bundle install"
serve = "bundle exec jekyll serve"

[dependencies]
ruby = ">=3.4.7,<4"
compilers = ">=1.11.0,<2"
